name: Build

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    strategy:
      matrix:
        os: ["ubuntu-latest", "windows-latest", "macos-latest"]

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.25.3'

      - name: Install dependencies (macOS)
        if: runner.os == 'macOS'
        run: brew install opus

      - name: Build
        if: runner.os != 'macOS'
        run: go build -o out/ .

      - name: Build (macOS)
        if: runner.os == 'macOS'
        run: |
          GOOS=darwin GOARCH=arm64 CGO_ENABLED=1 CC="clang" go build -o out/mumble-music-bot_arm64 .
          GOOS=darwin GOARCH=amd64 CGO_ENABLED=1 CC="clang" CFLAGS="-arch x86_64" go build -o out/mumble-music-bot_x86_64 .
          cp /opt/homebrew/opt/opus/lib/libopus.0.dylib out/
          chmod +x out/*
          install_name_tool -change /opt/homebrew/opt/opus/lib/libopus.0.dylib @executable_path/libopus.0.dylib out/mumble-music-bot_arm64
          lipo -create -output out/mumble-music-bot out/mumble-music-bot_arm64 out/mumble-music-bot_x86_64
          rm out/mumble-music-bot_arm64 out/mumble-music-bot_x86_64

      - name: Set output OS target name (Windows)
        if: runner.os == 'Windows'
        run: echo "OS_NAME=windows_x86_64" >> $env:GITHUB_ENV

      - name: Set output OS target name (Linux)
        if: runner.os == 'Linux'
        run: echo "OS_NAME=linux_x86_64" >> "$GITHUB_ENV"

      - name: Set output OS target name (macOS)
        if: runner.os == 'macOS'
        run: echo "OS_NAME=macos_universal" >> "$GITHUB_ENV"

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-${{ env.OS_NAME }}
          path: out/
